/*-----------------------------------------------------------------------------------------
 LIBRARY: MODELLING_LANGUAGE
 FILE: handling_errors

-----------------------------------------------------------------------------------------*/
// Handling errors
/*
	Standard error code
	Program uses an international standard for representing the error codes. The standard is documented in reference [ARP5571] and it was created in the gas turbine industry but can be use on any other discipline. In this standard, the error code is known as ESI (Engineering Status Indicator). 
	An ESI is an eight- or nine-digit integer: the first one or two digits indicate severity, the next three digits indicate purpose, the next two digits indicate category and the final two digits indicate the organization or tool or library responsible for the error. 
	The ESI integer then has the following form (each letter represents a digit):
	S(S)PPPCCOO
	Where:
	 	S(S) = Severity
	 	PPP = Purpose
	 	CC = Category
	 	OO = Owner
	The severity attribute not only conveys status information about a simulation case, it also controls the execution behavior of the model when an error is encountered. Here are the valid severity codes and the corresponding behaviors.
	 	99 :FATAL  kill run.
	 	9  :KILLPOINT  kill point but execute next point.
	 	8  :ERROR complete point and execute next point. 
	 	1-7 :WARNING  complete point and execute next point. 
	 	Other value: Not allowed.
	The three Purpose digits represent the main error code in Program. Each organization is free to define conventions for these values. This code identifies the exact type of error. It is a number between 001 and 999. The current error list in Program is included in the appendix D entitled.
	The following two-digit category indicators are used to display the category of the error. This category code is not used for the moment in Program and code 01 is used all the time. Any company can create other category codes if necessary (eg. arithmetic exception, convergence problems, input files, fluid properties, semantic error, invalid inputs, constrained violated, etc.).
	The last two digits are used to represent the organization or software tool raising the error. Program uses code 98 in all errors. Other organizations could use two different digits to identify properly who raises this error. This code plus the three digits purpose code represents a unique error.
	The ESI code can be represented as an integer value such as 992460198 or in string format  In this example the meaning of this error is:
	 	99- It is a FATAL error, it will stop the simulation.
	 	246- The error code is related with interpolation in tables. The message associated for this error is .
	 	01- Category (not used for the moment).
	 	98- The error has been generated by Program.
	There are two types of errors in Program:
	 	Errors generated internally by Program. All potential errors are listed in appendix D entitled .
	 	Errors generated by any library developer with the issueError() function. 
	 	
	1.15.9.2. 	How to create new errors
	The issueError() function can be used to generate error messages from the EL code by any developer in Program. Its syntax is as follows:
	NO_TYPE issueError(IN INTEGER errorId, 
	Where errorId is the error number to be displayed. The three dots mean that it can take a variable number of arguments. Normally these arguments are used to pass the values of variables to be printed in the error message (in a similar way to the WRITE() function).
	The user needs to create a file with error codes for each library in the following way:
	 	Create a text file called LIBNAME.errors.txt and place it just below the directory of the library. For example, if the library is ELECTRICAL, the file will be called ELECTRICAL.errors.txt and will be in the ELECTRICAL directory.
	 	The file format must include a header with the field names separated by tabs. Below it, each row is used for a different error code. For example:
	CODE	SEV	CAT	SOURCE	MESSAGE
	255	9	24	98	     The beta(BETA=%g) is too high
	256	99	25	98	     The compressor is out out limits (%g,%g)
	Where:
	 	CODE is the number of the error code. Codes 212, 213,214, 215 and 216 are reserved for the different types of assertions, and so should not be used.
	 	SEV is the severity, as follows:
	 	Fatal:     99
	 	Killpoint: 9
	 	Error:     8
	 	Warning:   1-7
	 	CAT is the category, which can be any positive two-digit number.
	 	SOURCE is the source of the error, represented by a two-digit positive integer. Except for code 98, the user can take any number. Several conventions could be used: using a unique number representing the company, creating a different code for each library developed by the organization, etc. 
	 	MESSAGE is the message to be displayed in the event of error and has a free format. If an argument is required, one of the following may be used:
	 	%d integer
	 	%g real
	 	%s string
	In this way, arguments can be passed to the function when it is called, similar to the EL WRITE() statement.
	For example, to create a new error, with code 312, type KILLPOINT, category 22 and source 45, the message has to inform that a value is outside the limits, and has to print both the value and the limit, which are passed to it as arguments.
	To do this, a new entry needs to be made in the error file, as follows:
	CODE	SEV	CAT	SOURCE	MESSAGE
	312	9 	22	45	The variable %s with value %g is out of limits(%g,%g)
	If the function is then called from the library where this error file is located:
	issueError(312,"speed",4.54, 5.5, 10.5)
	And it is executed, the following message is printed:
	*** KILLPOINT level 2 (code 9:312:22:45) path: .) in file "exp1.exp" at line 14 ***
	The variable speed with value 4.54 is out of limits(5.5,10.5)
	The error message not only shows the text, but also the arguments passed in the call. In this example, the current point will stop and the program will continue with the next one.
	
	1.15.9.3. 	How to get the final list of errors programmatically
	After performing any calculation with the tool, users may want to obtain the errors and warnings that were produced during the calculation. This capability can be used for many purposes: to write a list of all the errors in a file, to obtain the most severe error and proceed accordingly, etc.
	All the errors are returned by error codes as objects of ERROR_INFO type. Objects of this type have diverse methods that return different error parameters. It is important to note that if the same error is repeated it is returned only as one object. The user can call a method to know the number of occurrences.
	The definition of class ERROR_INFO is as follows:
	EXTERN CLASS ERROR_INFO
	    METHODS
	        EXTERN METHOD NO_TYPE clear()
	        EXTERN METHOD STRING msg()
	        EXTERN METHOD STRING esiCode()
	        EXTERN METHOD INTEGER esiAsNumber()
	        EXTERN METHOD INTEGER severity()
	        EXTERN METHOD INTEGER errorCode()
	        EXTERN METHOD INTEGER category()
	        EXTERN METHOD INTEGER source()
	        EXTERN METHOD STRING statusStr()
	        EXTERN METHOD INTEGER count()
	END CLASS
	The purpose of the methods is the following:
	 	clear() clears the object.
	 	msg() returns the message error. It is important to note that if this error has been produced multiple times only the first string message is kept.
	 	esiCode() returns the ESI string code of the error (e.g. "ESI:7:125:12:98").
	 	esiAsNumber() returns the ESI in numerical format (e.g. 71251298).
	 	severity() returns the error severity code (0 Not, 7 Warning, 8 Error, 9 Killpoint, 99 Fatal).
	 	errorCode() returns the error number (eg 876).
	 	category() returns the error category number (eg 12 for GUI).
	 	source() returns the error source number. For example, by default it will be 98 for the tool, but if users create their own errors in their library.
	 	statusStr() returns a string with the current status of the calculation (eg "INTEG_CINT", "STEADY_OK", etc).
	 	count() returns the total number of occurrences of a particular error.
	
	There are a number of functions for obtaining the errors during a simulation:
	"C++" FUNCTION INTEGER       numberOfErrors()
	"C++" FUNCTION ERROR_INFO    getErrorInfo(INTEGER i)
	"C++" FUNCTION NO_TYPE       resetErrorsLog()
	"C++" FUNCTION INTEGER       getErrorIndexWithMaxSeverity()
	- numberOfErrors() returns the number of errors. It is important to note that if the same error (eg division by zero) is repeated it will be stored only once. The count() method of the ERROR_INFO object can be used to know how many occurrences exist for that error.
	- getErrorInfo(i) returns the error object on the i'th position.
	- resetErrorsLog() clears the system error list.
	- getErrorIndexWithMaxSeverity() returns the error code with maximum severity. For example, if there is a WARNING in position 1 and a FATAL error in position 2, it returns a 2.
*/
COMPONENT comp_handlingErrors
   DECLS
        REAL x
        REAL y
    INIT
        x= 3
        y= 4
    CONTINUOUS
        x' = sin(TIME)
        y= x + 2
END COMPONENT